name    'alkivi-owncloud'
version '0.0.1'
source 'https://github.com/alkivi-sas/puppet-owncloud'
author 'alkivi'
license 'LGPLv3'
summary 'Controls owncloud deployement'
project_page 'https://github.com/alkivi-sas/puppet-owncloud'
dependency 'puppetlabs/stdlib', '>3.x'
dependency 'puppetlabs/apache', '>1.0.1'
dependency 'puppetlabs/vcsrepo', '>0.2.0'
dependency 'example42/php', '>2.0.18'
dependency 'puppetlabs/git', '>0.0.3'
dependency 'puppetlabs/mysql', '>2.2.3'